### ISSUE TITLE
support for remote terminals when editing over tramp ssh

### ISSUE THREAD

**Issue by wbolster** [davidshepherd7/terminal-here#11]
opening a remote ssh shell in the correct directory would be awesome.

(fwiw, this feature works in nautilus, the gnome file browser, which uses gvfs.)

**Comment by wbolster** [comment]
fwiw, the ssh command that gets executed by nautilus is this:

```
ssh -t host cd '/path/to/dir' && exec $SHELL -
```

**Comment by davidshepherd7** [comment]
Yeah this would be cool, and shouldn't be too hard to implement. I'll look into it when I get a chance, possibly this weekend sometime.

**Comment by wbolster** [comment]
fyi, gnome-terminal, xterm and the x-term-emulator on linux take a -c (or -e, cannot remember now, typing this on phone) to launch a terminal with a command.

**Comment by davidshepherd7** [comment]
This might work now. It works for me at least, and I wrote some tests which pass!

Let me know if you have any issues :+1:

**Comment by wbolster** [comment]
awesome, i'm gonna give this a try later. thanks!
