### ISSUE TITLE
terminal-here-project-root-function ignores projectile

### ISSUE THREAD

**Issue by wigust** [davidshepherd7/terminal-here#17]
`(cl-find-if 'fboundp '(projectile-project-root vc-root-dir))` from `terminal-here-project-root-function` doesn't find `projectile-project-root`.  Reevaluating `terminal-here-project-root-function` helps.

**Comment by davidshepherd7** [comment]
Ah, is `terminal-here` is loaded before `projectile` in your dotfiles? I think that would cause this.

**Comment by davidshepherd7** [comment]
Can you give the version I've just pushed a try? I think it should fix this issue.

Thanks for reporting it :+1:
