### ISSUE TITLE
Re-using existing Windows Terminal when one is already open at cwd

### ISSUE THREAD

**Issue by srustamo** [davidshepherd7/terminal-here#24]
I'm trying to figure out if it is possible to re-use an already open Windows Terminal window if one is already open at the cwd.

Any ideas how to go about it?

**Comment by davidshepherd7** [comment]
You might be able to try something based on recording the PID (I assume windows has those) every time you create a new terminal, and only open a new one if the old one has finished?

**Comment by srustamo** [comment]
If you can, please leave this open for a while, perhaps someone might chime in.

**Comment by QiangF** [comment]
You definitely need a way to talk with the terminal. Guake is a dropdown terminal that can be queried with dbus, see
https://github.com/SleepyBag/dropdown-remote

**Comment by QiangF** [comment]
Guake is linux only though.

**Comment by QiangF** [comment]
I can reuse guake tab with this :

    (use-package terminal-here
    :config
    (defun my-terminal-here-terminal-command (dir)
        (list "guake" "-s" "0" "--show" "-e"
            (concat "cd \"" (shell-quote-argument dir) "\"")))
    (setq terminal-here-terminal-command 'my-terminal-here-terminal-command))

**Comment by davidshepherd7** [comment]
I'll close this now since it's outside the scope of this project.

Why: looking up the terminal with a specific pwd and raising it in a window manager is something that would be better implemented by the terminal emulator itself.
