### ISSUE TITLE
Tag Releases

### ISSUE THREAD

**Issue by jgarte** [davidshepherd7/terminal-here#33]
Hi,

Are there any plans to continue making tagged releases or should package maintainers follow your commits?

I'm planning to package terminal-here for [guix](guix.gnu.org).

**Comment by davidshepherd7** [comment]
I guess that depends how much you prefer stability over new features/bug fixes. I don't think I've ever shipped a major bug or breaking change in this package to unstable so far, but it might happen eventually. Also my track record (across all my packages) of remembering to tag stable releases soon after the corresponding unstable release is not great (usually takes me 6 months to a year). I would probably follow master.

Thanks for the reminder though, I've just tagged 2.0 :)
