### ISSUE TITLE
Rename or alias `terminal-here-launch`

### ISSUE THREAD

**Issue by Silex** [davidshepherd7/terminal-here#5]
I propose that you rename or alias `terminal-here-launch` to `terminal-here`

It's better for when calling it like `M-x terminal-here`

I can make a PR if you want, but first I want to know if you're ok with the idea :wink:

**Comment by davidshepherd7** [comment]
Good idea thanks, I've just implemented it since it's so straightforward :smiley:

**Comment by Silex** [comment]
:+1:
