### ISSUE TITLE
autoload terminal-here-launch-in-directory

### ISSUE THREAD

**Issue by wbolster** [davidshepherd7/terminal-here#8]
the `terminal-here-launch-in-directory` function could be an autoload since this seems to be the "programmatic interface" entry point.

**Comment by wbolster** [comment]
oh, and thanks for this package. it worked out of the box with very sensible defaults like using `projectile-root`.

**Comment by davidshepherd7** [comment]
Hmm, I was under the impression that autoloads were normally used for interactive entry points only. For programmatic use I would expect the autoloads to be on the top-level interactive function, and when it is called it loads whatever libraries it needs with `require` as part of loading the rest of the package.

I can't really find any official documentation on this, all I found was [this](http://www.lunaryorn.com/posts/autoloads-in-emacs-lisp.html) which seems to agree.

I'm happy to change my mind though, if you can point me to something that explains when/why it is useful to autoload non-interactive things :+1:

**Comment by wbolster** [comment]
i think you may be right.
